x-common: &common-service
  user: ${MY_ID}:${MY_GROUP}
  network_mode: "host"

x-volumes: &service-volumes
  volumes:
    - &wma-admin "${HOST_MOUNT_DIR}/admin/wmagent:/data/admin/wmagent/"
    - &passwd "/etc/passwd:/etc/passwd:ro"
    - &group "/etc/group:/etc/group:ro"
    - &sudoers "/etc/sudoers:/etc/sudoers:ro"
    - &sudoersd "/etc/sudoers.d:/etc/sudoers.d:ro"
    - &certs "${HOST_MOUNT_DIR}/certs:/data/certs"

services:
  mariadb:
    <<: *common-service
    image: registry.cern.ch/cmsweb/mariadb:${MDB_TAG}
    container_name: mariadb
    volumes:
      - "/tmp:/tmp"
      - *certs
      - "${HOST_MOUNT_DIR}/srv/mariadb/${MDB_TAG}/install/database:/data/srv/mariadb/current/install/database"
      - "${HOST_MOUNT_DIR}/srv/mariadb/${MDB_TAG}/logs:/data/srv/mariadb/current/logs"
      - "${HOST_MOUNT_DIR}/admin/mariadb:/data/admin/mariadb/"
      - *wma-admin
      - *passwd
      - *group
      - *sudoers
      - *sudoersd
    hostname: ${MY_HOSTNAME}

  couchdb:
    <<: *common-service
    image: registry.cern.ch/cmsweb/wmagent-couchdb:${COUCH_TAG}
    container_name: couchdb
    volumes:
      - "/tmp:/tmp"
      - *certs
      - "${HOST_MOUNT_DIR}/srv/couchdb/${COUCH_TAG}/install:/data/srv/couchdb/current/install"
      - "${HOST_MOUNT_DIR}/srv/couchdb/${COUCH_TAG}/logs:/data/srv/couchdb/current/logs"
      - "${HOST_MOUNT_DIR}/srv/couchdb/${COUCH_TAG}/state:/data/srv/couchdb/current/state"
      - "${HOST_MOUNT_DIR}/srv/couchdb/${COUCH_TAG}/config:/data/srv/couchdb/current/config"
      - "${HOST_MOUNT_DIR}/admin/couchdb:/data/admin/couchdb/"
      - *wma-admin
      - *passwd
      - *group
      - *sudoers
      - *sudoersd

  wmagent: &wma-base
    <<: *common-service
    image: registry.cern.ch/cmsweb/wmagent:${WMA_TAG}
    volumes:
      - "/etc/condor:/etc/condor:ro"
      - "/tmp:/tmp"
      - *certs
      - "${HOST_MOUNT_DIR}/srv/wmagent/${WMA_TAG}/install:/data/srv/wmagent/current/install"
      - "${HOST_MOUNT_DIR}/srv/wmagent/${WMA_TAG}/logs:/data/srv/wmagent/current/logs"
      - "${HOST_MOUNT_DIR}/srv/wmagent/${WMA_TAG}/state:/data/srv/wmagent/current/state"
      - "${HOST_MOUNT_DIR}/srv/wmagent/${WMA_TAG}/config:/data/srv/wmagent/current/config"
      - *wma-admin
      - *passwd
      - *group
      - *sudoers
      - *sudoersd
    depends_on:
      - mariadb
      - couchdb
  
  wmcore-pr-pylint:
    image: registry.cern.ch/cmsweb/wmcore-dev:latest
    tty: true
    network_mode: "host"
    environment:
      - ghprbPullId=${ghprbPullId}
      - ghprbTargetBranch=${ghprbTargetBranch}
      - MY_ID
      - MY_GROUP
      - BUILD_ID
    command: ["/bin/bash"]
    volumes:
      - *passwd
      - *group
      - *sudoers
      - *sudoersd
      - "${HOST_MOUNT_DIR}/artifacts/:/home/cmsbld/artifacts/:Z"
  
  wmcore-unittests:
    <<: *wma-base
    image: registry.cern.ch/cmsweb/wmcore-dev:20240925
    network_mode: "host"
    environment:
      - MY_ID
      - MY_GROUP
      - WMA_CONFIG_FILE
      - BUILD_ID
    user: root
    pull_policy: always
    volumes:
      - "/etc/condor:/etc/condor:ro"
      - "/tmp:/tmp"
      - "/cvmfs:/cvmfs"
      - *certs
      - "${HOST_MOUNT_DIR}/srv/wmagent/${WMA_TAG}/install:/data/srv/wmagent/current/install"
      - "${HOST_MOUNT_DIR}/srv/wmagent/${WMA_TAG}/logs:/data/srv/wmagent/current/logs"
      - "${HOST_MOUNT_DIR}/srv/wmagent/${WMA_TAG}/state:/data/srv/wmagent/current/state"
      - "${HOST_MOUNT_DIR}/srv/wmagent/${WMA_TAG}/config:/data/srv/wmagent/current/config"
      - *wma-admin
      - *passwd
      - *group
      - *sudoers
      - *sudoersd
      - "${HOST_MOUNT_DIR}/artifacts/:/home/cmsbld/artifacts/:Z"
